language: generic 
sudo: required
service: 
    - docker

before_install:
    - docker build -t carlosfn224/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true carlosfn224/docker-react npm run test